{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 16,
   "id": "dbebba1e-46e9-4445-bddf-3dfdd0b86959",
   "metadata": {
    "collapsed": true,
    "jupyter": {
     "outputs_hidden": true
    }
   },
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "2025-05-02 23:21:01.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.305 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.306 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.307 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.308 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.309 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.311 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.312 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.313 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.313 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.314 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.316 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.317 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.318 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.319 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.320 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.320 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.323 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.324 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.326 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.327 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.328 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.329 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.331 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.332 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.333 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.334 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.335 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "C:\\Users\\MSI\\AppData\\Local\\Temp\\ipykernel_9016\\1857503485.py:81: FutureWarning: \n",
      "\n",
      "Passing `palette` without assigning `hue` is deprecated and will be removed in v0.14.0. Assign the `x` variable to `hue` and set `legend=False` for the same effect.\n",
      "\n",
      "  sns.countplot(data=df, x='Decade', palette='viridis', ax=ax1)\n",
      "2025-05-02 23:21:01.427 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.568 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.569 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.570 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.591 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.745 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:01.746 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.280 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.440 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.441 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.442 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.442 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.443 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.445 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.446 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.447 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.448 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.449 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.452 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.453 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.455 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.458 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:02.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:03.074 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:03.459 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:03.460 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:03.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:03.461 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:03.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n",
      "2025-05-02 23:21:03.462 Thread 'MainThread': missing ScriptRunContext! This warning can be ignored when running in bare mode.\n"
     ]
    },
    {
     "data": {
      "text/plain": [
       "DeltaGenerator()"
      ]
     },
     "execution_count": 16,
     "metadata": {},
     "output_type": "execute_result"
    }
   ],
   "source": [
    "import streamlit as st\n",
    "import pandas as pd\n",
    "import matplotlib.pyplot as plt\n",
    "import seaborn as sns\n",
    "from wordcloud import WordCloud\n",
    "from pymongo import MongoClient\n",
    "\n",
    "\n",
    "# Set up page configuration\n",
    "st.set_page_config(\n",
    "    page_title=\"AFI Top 100 Movies Analysis\",\n",
    "    page_icon=\"🎬\",\n",
    "    layout=\"wide\"\n",
    ")\n",
    "\n",
    "# Title and introduction\n",
    "st.title(\"🎬 AFI's 100 Years...100 Movies Analysis\")\n",
    "st.markdown(\"\"\"\n",
    "An interactive exploration of the American Film Institute's list of the 100 greatest American movies.\n",
    "\"\"\")\n",
    "\n",
    "# Connect to MongoDB\n",
    "@st.cache_resource\n",
    "def get_data():\n",
    "    client = MongoClient('mongodb://localhost:27017/')\n",
    "    db = client['movie_database']\n",
    "    collection = db['afi_top_100']\n",
    "    data = list(collection.find({}, {'_id': 0}))\n",
    "    return pd.DataFrame(data)\n",
    "\n",
    "df = get_data()\n",
    "\n",
    "# Convert year to numeric (just in case)\n",
    "df['Release year'] = pd.to_numeric(df['Release year'])\n",
    "\n",
    "# Sidebar filters\n",
    "st.sidebar.header(\"Filter Options\")\n",
    "selected_decades = st.sidebar.multiselect(\n",
    "    \"Select Decades\",\n",
    "    options=sorted((df['Release year'] // 10 * 10).unique()),\n",
    "    default=sorted((df['Release year'] // 10 * 10).unique())  # Fixed missing parenthesis\n",
    ")\n",
    "\n",
    "selected_directors = st.sidebar.multiselect(\n",
    "    \"Select Directors\",\n",
    "    options=sorted(df['Director'].unique()),\n",
    "    default=[]\n",
    ")\n",
    "\n",
    "# Apply filters\n",
    "if selected_decades:\n",
    "    df = df[(df['Release year'] // 10 * 10).isin(selected_decades)]\n",
    "if selected_directors:\n",
    "    df = df[df['Director'].isin(selected_directors)]\n",
    "\n",
    "# Main content tabs\n",
    "tab1, tab2, tab3, tab4 = st.tabs([\"Dataset\", \"Visualizations\", \"Statistics\", \"Word Cloud\"])\n",
    "\n",
    "with tab1:\n",
    "    st.header(\"Movie Dataset\")\n",
    "    st.dataframe(df.sort_values('Release year'), use_container_width=True)\n",
    "    \n",
    "    st.download_button(\n",
    "        label=\"Download Data as CSV\",\n",
    "        data=df.to_csv(index=False).encode('utf-8'),\n",
    "        file_name='afi_top_100_movies.csv',\n",
    "        mime='text/csv'\n",
    "    )\n",
    "\n",
    "with tab2:\n",
    "    st.header(\"Data Visualizations\")\n",
    "    \n",
    "    col1, col2 = st.columns(2)\n",
    "    \n",
    "    with col1:\n",
    "        st.subheader(\"Movies by Decade\")\n",
    "        df['Decade'] = (df['Release year'] // 10) * 10\n",
    "        fig1, ax1 = plt.subplots(figsize=(10, 6))\n",
    "        sns.countplot(data=df, x='Decade', palette='viridis', ax=ax1)\n",
    "        plt.xticks(rotation=45)\n",
    "        st.pyplot(fig1)\n",
    "    \n",
    "    with col2:\n",
    "        st.subheader(\"Top Directors\")\n",
    "        fig2, ax2 = plt.subplots(figsize=(10, 6))\n",
    "        df['Director'].value_counts().head(10).plot(kind='barh', color='darkred', ax=ax2)\n",
    "        st.pyplot(fig2)\n",
    "    \n",
    "    st.subheader(\"Movies by Year\")\n",
    "    fig3, ax3 = plt.subplots(figsize=(12, 4))\n",
    "    sns.histplot(data=df, x='Release year', bins=30, kde=True, ax=ax3)\n",
    "    st.pyplot(fig3)\n",
    "\n",
    "with tab3:\n",
    "    st.header(\"Key Statistics\")\n",
    "    \n",
    "    col1, col2 = st.columns(2)\n",
    "    \n",
    "    with col1:\n",
    "        st.subheader(\"Time Range\")\n",
    "        st.metric(\"Earliest Film\", df['Release year'].min())\n",
    "        st.metric(\"Latest Film\", df['Release year'].max())\n",
    "        \n",
    "        st.subheader(\"Most Frequent Director\")\n",
    "        top_director = df['Director'].mode()[0]\n",
    "        st.metric(\"Director with most films\", f\"{top_director} ({df['Director'].value_counts().max()} films)\")\n",
    "    \n",
    "    with col2:\n",
    "        st.subheader(\"Decade Distribution\")\n",
    "        decade_counts = (df['Release year'] // 10 * 10).value_counts().sort_index()\n",
    "        st.table(decade_counts)\n",
    "        \n",
    "        st.subheader(\"Directors with Multiple Films\")\n",
    "        multi_film_directors = df['Director'].value_counts()[df['Director'].value_counts() > 1]\n",
    "        st.table(multi_film_directors)\n",
    "\n",
    "with tab4:\n",
    "    st.header(\"Movie Titles Word Cloud\")\n",
    "    wordcloud = WordCloud(width=800, height=400, background_color='white').generate(' '.join(df['Film']))\n",
    "    fig, ax = plt.subplots(figsize=(12, 6))\n",
    "    ax.imshow(wordcloud, interpolation='bilinear')\n",
    "    ax.axis('off')\n",
    "    st.pyplot(fig)\n",
    "\n",
    "# Footer\n",
    "st.markdown(\"---\")\n",
    "st.markdown(\"\"\"\n",
    "**Data Source**: [Wikipedia - AFI's 100 Years...100 Movies](https://en.wikipedia.org/wiki/AFI%27s_100_Years...100_Movies)  \n",
    "**Analysis**: Interactive exploration of the American Film Institute's top 100 films  \n",
    "**Note**: Data was scraped from Wikipedia and stored in MongoDB\n",
    "\"\"\")\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.2"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
